# Base image
FROM centos:8

# Update system and install dependencies
RUN dnf -y update && \
    dnf -y install epel-release git make automake cmake3 gcc-c++ libpcap-devel

# Install Python 3 and pip
RUN dnf -y install python3 python3-pip && \
    pip3 install -U pip

# Install robot dependencies
RUN dnf -y install postgresql-devel python3-docker python3-netaddr python38-pip && \
    pip3 install matplotlib

# Install lispflowmapping dependencies
RUN dnf -y install boost-devel libxml2-devel libxslt-devel

# Clone and install udpreplay
RUN git clone https://github.com/ska-sa/udpreplay.git /tmp/udpreplay && \
    cd /tmp/udpreplay && \
    ./bootstrap.sh && \
    ./configure && \
    make && \
    make install && \
    cd / && \
    rm -rf /tmp/udpreplay

# Clean-up
RUN dnf -y remove epel-release git make automake cmake3 gcc-c++ && \
    dnf clean all

# Set the working directory
WORKDIR /

# Define the command to run within the container
CMD ["echo", "Docker container built successfully!"]

