name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-run-docker-image:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t ${{ vars.REPOSITORY }}/${{ vars.IMAGENAME }} robot/
      
      - name: Test
        run: docker run -p 8181:8181 --env FEATURES=odl-restconf,odl-netconf-topology opendaylight/opendaylight:0.18.1 &&/
             docker run ${{ vars.REPOSITORY }}/${{ vars.IMAGENAME }} bash -c 'yum install -y git python3-pip && pip3 install robotframework robotframework-extendedrequestslibrary && git clone https://github.com/opendaylight/integration-test.git && cd integration-test/csit/suites/aaa/authn && robot -L debug --variable USER_HOME:/home/centos --variable DEFAULT_LINUX_PROMPT:\$ --variable ODL_SYSTEM_IP:127.0.0.1 --variable ODL_SYSTEM_USER:centos ./Restconf_Basic_Auth.robot'
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
