name: Build and Run Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-Test-Robot-docker-image:
    runs-on: ubuntu-latest

    services:
      opendaylight:
        image: opendaylight/opendaylight:0.18.1
        env:
          FEATURES: odl-restconf,odl-netconf-topology
        ports:
          - 8181:8181
        options: --name odl-container
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: docker build -t ${{ vars.REPOSITORY }}/${{ vars.IMAGENAME }} robot/        

      - name: Test   
        run: |
          docker run --name test-robot --network container:odl-container ${{ vars.REPOSITORY }}/${{ vars.IMAGENAME }} bash -c 'yum install -y git python3-pip && pip3 install robotframework robotframework-extendedrequestslibrary && git clone https://github.com/opendaylight/integration-test.git && cd integration-test/csit/suites/integration/basic && robot -L debug --variable USER_HOME:/home/centos --variable DEFAULT_LINUX_PROMPT:\$ --variable ODL_SYSTEM_IP:opendaylight --variable ODL_SYSTEM_USER:centos ./restconf_modules.robot'


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: docker push ${{ vars.REPOSITORY }}/${{ vars.IMAGENAME }}
