name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  Docker-Images-build-odl-java-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Build Docker image
        run: docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGENAME }} .
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ env.REPOSITORY }}/${{ env.IMAGENAME }} 

  Docker-image-build-robot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Build Docker image
        run: docker build -t ${{ env.REPOSITORY }}/${{ env.IMAGENAME }} /robot/
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push Docker image
        run: docker push ${{ env.REPOSITORY }}/${{ env.IMAGENAME }}
