name: CSIT-1-Node-Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:

  daexim-csit-1-node-argon:
    runs-on: ubuntu-latest

    env:  # Set the environment variable for the daexim test suite
      suite: daexim

    steps:
      - name: Include run-test workflow for daexim
        uses: ./.github/workflows/run-test.yml

  aaa-csit-1-node-authn-all-argon:
    runs-on: ubuntu-latest

    env:  # Set the environment variable for the aaa test suite
      suite: aaa

    steps:
      - name: Include run-test workflow for aaa
        uses: ./.github/workflows/run-test.yml

  # Add similar jobs for other test suites as needed
