name: CSIT-1-Node-Test

on:
  push:

jobs:
  daexim-csit-1-node-argon:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        suite: ["daexim"]

    steps:
      - name: Include run-test workflow
        uses: .github/workflows/run-test.yml
        with:
          suite: ${{ matrix.suite }}

  aaa-csit-1-node-authn-all-argon:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        suite: ["aaa"]

    steps:
      - name: Include run-test workflow
        uses: .github/workflows/run-test.yml
        with:
          suite: ${{ matrix.suite }}

  distribution-csit-1-node-userfeatures-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        suite: ["distribution"]

    steps:
      - name: Include run-test workflow
        uses: .github/workflows/run-test.yml
        with:
          suite: ${{ matrix.suite }}
