name: Run Test

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-test:
    runs-on: ubuntu-latest

    env:  # Define environment variables for the test suite
      SUITE: ${{ inputs.suite }}

    services:
      opendaylight:
        image: ${{ vars.REPOSITORY }}/${{ vars.ODL_IMAGE }}
        env:
          FEATURES: odl-restconf,odl-daexim-all,odl-netconf-topology,odl-jolokia
        ports:
          - 8181:8181
        options: --name odl-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # ... (rest of the steps)

      - name: Run Test
        run: |
          docker exec robot bash -c 'git clone https://github.com/opendaylight/integration-test.git &&       
            cd integration-test/csit/suites/${SUITE} &&  # Use the environment variable
            robot -L debug --variable USER_HOME:/root \
            --variable WORKSPACE:/home/youruser \
            -v BUNDLEFOLDER:karaf-0.18.1 \
            -v ODL_STREAM:argon \
            --variable DEFAULT_LINUX_PROMPT:\$ \
            --variable ODL_SYSTEM_USER:youruser \
            --variable ODL_SYSTEM_IP:opendaylight \
            --variable ODL_SYSTEM_1_IP:opendaylight \
            -v IS_KARAF_APPL:True \
            ./*.robot'
