name: CSIT-1-Node-Test

on:
  push:

jobs:
  daexim-csit-1-node-argon:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runs-on: ubuntu-latest
        suite: daexim

    steps:
      - name: Include run-test workflow for daexim
        uses: ./.github/workflows/run-test.yml
        with:
          runs-on: ${{ matrix.runs-on }}
          suite: ${{ matrix.suite }}

  aaa-csit-1-node-authn-all-argon:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runs-on: ubuntu-latest
        suite: aaa

    steps:
      - name: Include run-test workflow for aaa
        uses: ./.github/workflows/run-test.yml
        with:
          runs-on: ${{ matrix.runs-on }}
          suite: ${{ matrix.suite }}

  distribution-csit-1-node-userfeatures-all:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runs-on: ubuntu-latest
        suite: distribution

    steps:
      - name: Include run-test workflow for distribution
        uses: ./.github/workflows/run-test.yml
        with:
          runs-on: ${{ matrix.runs-on }}
          suite: ${{ matrix.suite }}
