name: csit

on:
  push:
    branches:
      - main

jobs:
  aaa-csit-1node-authn-all-argon:
    runs-on: ubuntu-latest

    services:
      opendaylight:
        image: opendaylight/opendaylight:0.18.1
        env:
          FEATURES: odl-restconf,odl-netconf-topology
        ports:
          - 8181:8181
        options: --name odl-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start robot container
        run: |
          docker run -d --name robot ayushishu/robot-base-image:latest tail -f /dev/null

      - name: Run Test
        run: |
           curl opendaylight:8181 && curl odl-container:8181'
